"""ilk tablolar

Revision ID: 708c28fb38b9
Revises: 
Create Date: 2026-07-21 14:09:55.238366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708c28fb38b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('art_id', sa.Integer(), nullable=False),
    sa.Column('article_name', sa.String(), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('art_id')
    )
    op.create_table('institutions',
    sa.Column('inst_id', sa.Integer(), nullable=False),
    sa.Column('inst_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('inst_id')
    )
    op.create_table('members',
    sa.Column('mem_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('mem_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('authors',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('uye_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.inst_id'], ),
    sa.ForeignKeyConstraint(['uye_id'], ['members.mem_id'], ),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('citations',
    sa.Column('cit_id', sa.Integer(), nullable=False),
    sa.Column('art_id', sa.Integer(), nullable=False),
    sa.Column('other_art_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['art_id'], ['articles.art_id'], ),
    sa.ForeignKeyConstraint(['other_art_id'], ['articles.art_id'], ),
    sa.PrimaryKeyConstraint('cit_id')
    )
    op.create_table('saved_searches',
    sa.Column('saveds_id', sa.Integer(), nullable=False),
    sa.Column('mem_id', sa.Integer(), nullable=False),
    sa.Column('search_name', sa.String(), nullable=False),
    sa.Column('saved_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['mem_id'], ['members.mem_id'], ),
    sa.PrimaryKeyConstraint('saveds_id')
    )
    op.create_table('search_history',
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('mem_id', sa.Integer(), nullable=False),
    sa.Column('search_date', sa.Date(), nullable=False),
    sa.Column('search_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['mem_id'], ['members.mem_id'], ),
    sa.PrimaryKeyConstraint('search_id')
    )
    op.create_table('middle',
    sa.Column('mid_id', sa.Integer(), nullable=False),
    sa.Column('art_id', sa.Integer(), nullable=False),
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['art_id'], ['articles.art_id'], ),
    sa.ForeignKeyConstraint(['auth_id'], ['authors.auth_id'], ),
    sa.PrimaryKeyConstraint('mid_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('middle')
    op.drop_table('search_history')
    op.drop_table('saved_searches')
    op.drop_table('citations')
    op.drop_table('authors')
    op.drop_table('members')
    op.drop_table('institutions')
    op.drop_table('articles')
    # ### end Alembic commands ###
